name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'install dependencies'
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: 'build with yarn'
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      - name: 'run unit tests'
        uses: borales/actions-yarn@v2.0.0
        with:
            cmd: test:unit
      - name: 'upload files to server using ssh'
        uses: horochx/deploy-via-scp@master
        with:
          local: dist/*
          remote: ${{ secrets.PATH }}
          host: ${{ secrets.SERVER }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.NextGN_SSH }}
